-- AddVarCharConstraints: add DB-level length limits to match Zod schemas

-- User
ALTER TABLE "User" ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE "User" ALTER COLUMN "email" TYPE VARCHAR(255);
ALTER TABLE "User" ALTER COLUMN "linkedIn" TYPE VARCHAR(500);
ALTER TABLE "User" ALTER COLUMN "gitHub" TYPE VARCHAR(500);
ALTER TABLE "User" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "User" ALTER COLUMN "major" TYPE VARCHAR(100);
ALTER TABLE "User" ALTER COLUMN "coopSummary" TYPE VARCHAR(1000);
ALTER TABLE "User" ALTER COLUMN "profileImageKey" TYPE VARCHAR(500);
ALTER TABLE "User" ALTER COLUMN "googleImageURL" TYPE VARCHAR(500);

-- Alumni
ALTER TABLE "Alumni" ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE "Alumni" ALTER COLUMN "email" TYPE VARCHAR(255);
ALTER TABLE "Alumni" ALTER COLUMN "linkedIn" TYPE VARCHAR(500);
ALTER TABLE "Alumni" ALTER COLUMN "gitHub" TYPE VARCHAR(500);
ALTER TABLE "Alumni" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "Alumni" ALTER COLUMN "image" TYPE VARCHAR(500);
ALTER TABLE "Alumni" ALTER COLUMN "quote" TYPE VARCHAR(2000);
ALTER TABLE "Alumni" ALTER COLUMN "previous_roles" TYPE VARCHAR(1000);

-- AlumniCandidate
ALTER TABLE "AlumniCandidate" ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "email" TYPE VARCHAR(255);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "linkedIn" TYPE VARCHAR(500);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "gitHub" TYPE VARCHAR(500);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "imageKey" TYPE VARCHAR(500);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "major" TYPE VARCHAR(100);
ALTER TABLE "AlumniCandidate" ALTER COLUMN "coopSummary" TYPE VARCHAR(1000);

-- AlumniRequest
ALTER TABLE "AlumniRequest" ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE "AlumniRequest" ALTER COLUMN "email" TYPE VARCHAR(255);
ALTER TABLE "AlumniRequest" ALTER COLUMN "linkedIn" TYPE VARCHAR(500);
ALTER TABLE "AlumniRequest" ALTER COLUMN "gitHub" TYPE VARCHAR(500);
ALTER TABLE "AlumniRequest" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "AlumniRequest" ALTER COLUMN "image" TYPE VARCHAR(500);
ALTER TABLE "AlumniRequest" ALTER COLUMN "quote" TYPE VARCHAR(2000);
ALTER TABLE "AlumniRequest" ALTER COLUMN "previous_roles" TYPE VARCHAR(1000);

-- Quote (expand from 255 to 2000)
ALTER TABLE "Quote" ALTER COLUMN "quote" TYPE VARCHAR(2000);
ALTER TABLE "Quote" ALTER COLUMN "author" TYPE VARCHAR(100);

-- GoLinks
ALTER TABLE "GoLinks" ALTER COLUMN "golink" TYPE VARCHAR(100);
ALTER TABLE "GoLinks" ALTER COLUMN "url" TYPE VARCHAR(500);
ALTER TABLE "GoLinks" ALTER COLUMN "description" TYPE VARCHAR(500);

-- Event
ALTER TABLE "Event" ALTER COLUMN "title" TYPE VARCHAR(200);
ALTER TABLE "Event" ALTER COLUMN "location" TYPE VARCHAR(200);
ALTER TABLE "Event" ALTER COLUMN "image" TYPE VARCHAR(500);
ALTER TABLE "Event" ALTER COLUMN "description" TYPE VARCHAR(2000);

-- Project
ALTER TABLE "Project" ALTER COLUMN "title" TYPE VARCHAR(200);
ALTER TABLE "Project" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "Project" ALTER COLUMN "progress" TYPE VARCHAR(1000);
ALTER TABLE "Project" ALTER COLUMN "repoLink" TYPE VARCHAR(500);
ALTER TABLE "Project" ALTER COLUMN "contentURL" TYPE VARCHAR(500);
ALTER TABLE "Project" ALTER COLUMN "projectImage" TYPE VARCHAR(500);

-- Sponsor
ALTER TABLE "Sponsor" ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE "Sponsor" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "Sponsor" ALTER COLUMN "logoUrl" TYPE VARCHAR(500);
ALTER TABLE "Sponsor" ALTER COLUMN "websiteUrl" TYPE VARCHAR(500);

-- PurchaseRequest
ALTER TABLE "PurchaseRequest" ALTER COLUMN "name" TYPE VARCHAR(200);
ALTER TABLE "PurchaseRequest" ALTER COLUMN "committee" TYPE VARCHAR(100);
ALTER TABLE "PurchaseRequest" ALTER COLUMN "description" TYPE VARCHAR(1000);
ALTER TABLE "PurchaseRequest" ALTER COLUMN "notifyEmail" TYPE VARCHAR(255);
ALTER TABLE "PurchaseRequest" ALTER COLUMN "receiptEmail" TYPE VARCHAR(255);
ALTER TABLE "PurchaseRequest" ALTER COLUMN "eventName" TYPE VARCHAR(200);
